### ISSUE TITLE
Version of OCP and BRMS

### ISSUE THREAD

**Issue by jeffreydelong** [redhatdemocentral/appdev-in-the-cloud-rhpds-workshops#1]
Is this demo going to be updated to OCP 3.11 and Decision Manager 7.1?

**Comment by eschabell** [comment]
There was regression in OCP 3.10 and 3.11 introducing dependency on a docker engine running in the background. We decided not to update to these versions awaiting 4.x series. There are no plans to update at this time.

(This project's actually moved over to gitlab, see first line in readme.)
